id: I9428569B
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:16:38.100082+00:00
last_modified: 2022-12-14 18:16:38.100104+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: tei
  datatype: Text
  eft-text-id: UT22084-044-005
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_85-The_Question_of_Maitreya-v1
bases:
  '5212':
    source_metadata: null
    order: 1
    base_file: 5212.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
